[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[images]
  remote_patterns = []

# Disable Netlify Image CDN
[functions]
  external_node_modules = ["sharp"]